name: spotify-display
services:
    client:
        build:
            context: ../
            dockerfile: ./docker/client.Dockerfile
            args:
                - SSL_CERT=${SSL_CERT}
                - SSL_KEY=${SSL_KEY}
                - SERVER_NAME=${SERVER_NAME}
                - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
                - REDIRECT_URI=${REDIRECT_URI}
        ports:
            - 80:80
            - 443:443
        env_file:
            - .dev.env
            - .local.env
